version: 2

models:
    - name: stg_local_bike__brands
      description: Table de référence standardisée des marques de vélos.
      columns:
        - name: brand_id
          description: identifiant unique des marques
          data_tests:
             - unique
             - not_null
    
        - name: brand_name
          description: nom de la marque

    - name: stg_local_bike__categories
      description: Table standardisée des catégories de produits.
      columns: 
        - name: category_id
          description: identifiant unique des catégories
          data_tests:
            - unique
            - not_null
        - name: category_name
          description : nom de chaque catégorie de vélo
    
    - name: stg_local_bike__customers
      description: Table de référence standardisée des clients.
      columns:
        - name: customer_id
          description: identifiant unique du client
          data_tests:
            - unique
            - not_null
        - name: first_name
          description: prénom du client
        - name: last_name
          description: nom de famille du client
        - name: phone
          description: numéro de téléphone du client
        - name: email
          description: adresse email du client
        - name: street
          description: nom de la rue du client
        - name: city
          description: ville du client
        - name: state
          description: état/région du client
        - name: zip_code
          description: code postal du client
    
    - name: stg_local_bike__order_items
      description: Table standardisée des lignes de commande.
      columns:
        - name: order_item_id
          description: identifiant unique de la ligne de commande (concaténation order_id + item_id)
          data_tests:
            - unique
            - not_null
        - name: order_id
          description: identifiant d’une commande client
        - name: item_id
          description: identifiant d’un item dans la commande
        - name: product_id
          description: identifiant du produit associé
        - name: quantity
          description: quantité de cet article dans la commande
        - name: list_price
          description: prix public avant remise
        - name: discount
          description: remise appliquée sur cet article
    
    - name: stg_local_bike__orders
      description: Table standardisée des commandes.
      columns:
        - name: order_id
          description: identifiant unique d’une commande
          data_tests:
            - unique
            - not_null
        - name: customer_id
          description: identifiant du client (clé étrangère)
          data_tests:
            - relationships:
                field: customer_id
                to: ref('stg_local_bike__customers')
        - name: order_status
          description: statut de traitement de la commande
        - name: order_date
          description: date de création de la commande
        - name: required_date
          description: date attendue de livraison
        - name: shipped_date
          description: date d’expédition
        - name: store_id
          description : identifiant unique du magasin associé (clé étrangère)
          data_tests:
            - relationships:
                field: store_id
                to: ref('stg_local_bike__stores')
        - name: staff_id
          description: identifiant du membre du personnel ayant géré la commande (clé étrangère)
          data_tests:
            - relationships:
                field: staff_id
                to: ref('stg_local_bike__staffs')
    
    - name: stg_local_bike__products
      description: Table standardisée des produits.
      columns : 
        - name: product_id
          description: identifiant unique d’un produit
          data_tests:
            - unique
            - not_null
        - name: product_name
          description : nom du produit
        - name: brand_id  
          description : identifiant de la marque (clé étrangère)
          data_tests:
            - relationships:
                field: brand_id
                to: ref('stg_local_bike__brands')
        - name: category_id
          description: identifiant de la catégorie (clé étrangère)
          data_tests:
            - relationships:
                field: category_id
                to: ref('stg_local_bike__categories')
        - name: model_year
          description: année du modèle
        - name: list_price
          description: prix public avant remise
    
    - name: stg_local_bike__staffs
      description : Table de référence des employés.
      columns: 
        - name: staff_id
          description: identifiant unique du membre du personnel
          data_tests:
            - unique
            - not_null
        - name: first_name
          description: prénom du membre du personnel
        - name: last_name
          description: nom du membre du personnel
        - name: email
          description: email du membre du personnel
        - name: phone
          description: numéro de téléphone du membre du personnel
        - name: active
          description: indique si l’employé est actuellement actif
        - name: store_id
          description : identifiant du magasin auquel le personnel est rattaché (clé étrangère)
          data_tests:
            - relationships:
                field: store_id
                to: ref('stg_local_bike__stores')
        - name: manager_id
          description: identifiant du manager du membre du personnel
    
    - name: stg_local_bike__stocks
      description: Niveau de stock actuel par magasin et par produit.
      columns: 
        - name: store_id
          description: identifiant du magasin (clé étrangère)
          data_tests:
            - relationships:
                field: store_id
                to: ref('stg_local_bike__stores')
        - name: product_id
          description: identifiant du produit (clé étrangère)
          data_tests:
            - relationships:
                field: product_id
                to: ref('stg_local_bike__products')
        - name: quantity
          description: quantité disponible en stock dans le magasin

    - name: stg_local_bike__stores
      description: Table de référence des magasins, incluant coordonnées et localisation.
      columns:
        - name: store_id
          description: identifiant unique du magasin
          data_tests:
            - unique
            - not_null
        - name: store_name
          description: nom du magasin
        - name: phone
          description: numéro de téléphone du magasin
        - name: email
          description: adresse email du magasin
        - name: street
          description: adresse du magasin (rue)
        - name: city
          description: ville où se situe le magasin
        - name: state
          description: état/région du magasin
        - name: zip_code
          description: code postal du magasin